### PR TITLE
Changes scripts, added files

### PR DESCRIPTION
**Pull request by skolome**
I added the files that were downloaded from other repositories, to this one. Changed the scripts, broke them into two-part install for each component, it seems to installing properly now, even nDPI.
Fixed pfbridge automatically working, now it should start at boot.

### CODE REVIEW

**Comment by mpeuster** [comment]
@skolome There seems to be an error in the build process:
```
Sending build context to Docker daemon 271.4 MB

16:06:43 Step 1 : LS 
16:06:43 Unknown instruction: LS
16:06:43 Build step 'Execute shell' marked build as failure
```

You can check the automated build process by executing `build.sh`in the `vnfs/` folder.

Can you als fetch the latest updates from the repo to resolve the merge conflicts?

**Comment by skolome** [comment]
updated branch, fixed Dockerfile

**Comment by mpeuster** [comment]
Thanks. Lets wait until Jenkins is back online on Monday :-)

**Comment by mpeuster** [comment]
test this please

**Comment by mpeuster** [comment]
test this please

**Pull request merged**
