### PR TITLE
Added a "sonata-vtc-service-sp" with private licence version named "s…

### PR DESCRIPTION
**Pull request by srodriguezOPT**
…onata-vtc-private-service-sp"

### CODE REVIEW

**Comment by srodriguezOPT** [comment]
test this please

**Comment by mpeuster** [comment]
Mhm. Jenkins seems not to be triggered. Maybe @felipevicens can help?

**Comment by srodriguezOPT** [comment]
Yes, me too with son-bss. It seems something related with the jenkins update.

**Comment by mpeuster** [comment]
Seems that there is a problem with son-validate: https://github.com/sonata-nfv/son-cli/issues/242
(however does not seem to be related to you service @srodriguezOPT, lets see if @lconceicao  has an idea)

**Comment by srodriguezOPT** [comment]
@mpeuster, @felipevicens

Take a look at the workspace. Not all the service-projects exists. Which branch is being used by jenkins?

**Comment by mpeuster** [comment]
The PR branch should be use, at least it was used with the old Jenkins version.

**Comment by felipevicens** [comment]
test this please

**Comment by mpeuster** [comment]
test this please

**Comment by srodriguezOPT** [comment]
test this please

**Comment by mpeuster** [comment]
Mhm good question. Maybe @lconceicao can help here. The job always uses the very latest son-cli tools installed from the master branch. Does the packaging work locally?

**Comment by srodriguezOPT** [comment]
@lconceicao , 

Is this the schema used for validation?
https://github.com/sonata-nfv/son-cli/blob/master/src/son/schema/tests/son-schema/nsd-schema.yml

It does not match with the son-schema latest one (licences field missing)

**Comment by lconceicao** [comment]
Hi @srodriguezOPT,

No, that schema is just for test and it is obsolete. I will look into this issue.

**Comment by lconceicao** [comment]
@srodriguezOPT,

Can you please increase the debug by adding the `--debug` option to the creation of workspace in pack.sh?

Like so:

`son-workspace --init --workspace test_ws --debug`

**Comment by srodriguezOPT** [comment]
test this please

**Comment by lconceicao** [comment]
test this please

**Comment by lconceicao** [comment]
The problem is solved. It was cached resources stored in the user home folder, since the job is running on master.

**Comment by mpeuster** [comment]
Great. Thanks @lconceicao . I'll merge the PR.

**Pull request merged**
